// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdqXoewKhagUVs1XB4K5SWzOGGTnNuEak',
    appId: '1:1095431222019:web:a67eb76c31f9d4230aef36',
    messagingSenderId: '1095431222019',
    projectId: 'smartnavi-d11ab',
    authDomain: 'smartnavi-d11ab.firebaseapp.com',
    storageBucket: 'smartnavi-d11ab.firebasestorage.app',
    measurementId: 'G-VVRZNLMVT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByBlcVNDIL_lJeH9wGiiSAXnjllpuSopk',
    appId: '1:1095431222019:android:53c7fa885daa6a170aef36',
    messagingSenderId: '1095431222019',
    projectId: 'smartnavi-d11ab',
    storageBucket: 'smartnavi-d11ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73QsCkziruKRHGkASljtpen_XNJKe7q4',
    appId: '1:1095431222019:ios:baede6d6705b015b0aef36',
    messagingSenderId: '1095431222019',
    projectId: 'smartnavi-d11ab',
    storageBucket: 'smartnavi-d11ab.firebasestorage.app',
    iosBundleId: 'app.tinyhacks.smartnavi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73QsCkziruKRHGkASljtpen_XNJKe7q4',
    appId: '1:1095431222019:ios:baede6d6705b015b0aef36',
    messagingSenderId: '1095431222019',
    projectId: 'smartnavi-d11ab',
    storageBucket: 'smartnavi-d11ab.firebasestorage.app',
    iosBundleId: 'app.tinyhacks.smartnavi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdqXoewKhagUVs1XB4K5SWzOGGTnNuEak',
    appId: '1:1095431222019:web:134cb29b039630a20aef36',
    messagingSenderId: '1095431222019',
    projectId: 'smartnavi-d11ab',
    authDomain: 'smartnavi-d11ab.firebaseapp.com',
    storageBucket: 'smartnavi-d11ab.firebasestorage.app',
    measurementId: 'G-0G8VB8ZWR3',
  );
}
